# Load .env variables if present
ifneq (,$(wildcard .env))
	include .env
	export
endif


.PHONY: up down rebuild build logs restart ps clean fresh \
	alembic-init migrate upgrade downgrade current history bump \
	dbshell dbtables

# =========================
# DOCKER
# =========================

# Start all services (API + Postgres) and build if needed
up:
	docker compose up --build

# Stop all containers
down:
	docker compose down

# Rebuild without cache (use when requirements/Dockerfile change)
build:
	docker compose build --no-cache

# Stop, rebuild without cache, and start again
rebuild:
	docker compose down
	docker compose build --no-cache
	docker compose up

# Force container recreation (useful if something gets stuck)
fresh:
	docker compose up --build --force-recreate

# Show live logs
logs:
	docker compose logs -f

# Restart services
restart:
	docker compose restart

# Show running services status
ps:
	docker compose ps

# Full reset (also removes Postgres volume)
clean:
	docker compose down -v --remove-orphans
	docker system prune -f


# =========================
# ALEMBIC
# =========================

# Initialize Alembic (run ONLY once). If alembic/ exists, do NOT run again.
alembic-init:
	docker compose exec api alembic init alembic

# Create an autogenerated migration
# Usage: make migrate m="create users table"
migrate:
	docker compose exec api alembic revision --autogenerate -m "$(m)"

# Apply all pending migrations
upgrade:
	docker compose exec api alembic upgrade head

# Roll back one migration
downgrade:
	docker compose exec api alembic downgrade -1

# Show current DB migration version
current:
	docker compose exec api alembic current

# Show migration history
history:
	docker compose exec api alembic history


# Create + apply a new migration in one command
# Usage: make bump m="add conversations table"
bump:
	@test -n "$(m)" || (echo "Usage: make bump m=\"your migration message\""; exit 1)
	docker compose exec api alembic revision --autogenerate -m "$(m)"
	docker compose exec api alembic upgrade head
	@echo ""
	@echo "✅ Done."
	@echo "Next time you change models:"
	@echo "  1) Edit/add model(s) in app/infrastructure/models/"
	@echo "  2) Ensure the model is imported in app/infrastructure/models/__init__.py"
	@echo "  3) Run: make bump m=\"describe the change\""


# =========================
# POSTGRES (utils)
# =========================

# Open psql inside the Postgres container
dbshell:
	docker compose exec postgres psql -U $(POSTGRES_USER) -d $(POSTGRES_DB)

# List all tables
dbtables:
	docker compose exec postgres psql -U $(POSTGRES_USER) -d $(POSTGRES_DB) -c "\dt"
